package Modele;
// Generated 2018-09-03 11:44:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Commandes generated by hbm2java
 */
public class Commandes  implements java.io.Serializable {


     private String idCommande;
     private ModesPaiement modesPaiement;
     private Clients clients;
     private String dateCommande;
     private Set factureses = new HashSet(0);
     private Set lignesCommandes = new HashSet(0);

    public Commandes() {
    }

	
    public Commandes(String idCommande, ModesPaiement modesPaiement, Clients clients, String dateCommande) {
        this.idCommande = idCommande;
        this.modesPaiement = modesPaiement;
        this.clients = clients;
        this.dateCommande = dateCommande;
    }
    public Commandes(String idCommande, ModesPaiement modesPaiement, Clients clients, String dateCommande, Set factureses, Set lignesCommandes) {
       this.idCommande = idCommande;
       this.modesPaiement = modesPaiement;
       this.clients = clients;
       this.dateCommande = dateCommande;
       this.factureses = factureses;
       this.lignesCommandes = lignesCommandes;
    }
   
    public String getIdCommande() {
        return this.idCommande;
    }
    
    public void setIdCommande(String idCommande) {
        this.idCommande = idCommande;
    }
    public ModesPaiement getModesPaiement() {
        return this.modesPaiement;
    }
    
    public void setModesPaiement(ModesPaiement modesPaiement) {
        this.modesPaiement = modesPaiement;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public String getDateCommande() {
        return this.dateCommande;
    }
    
    public void setDateCommande(String dateCommande) {
        this.dateCommande = dateCommande;
    }
    public Set getFactureses() {
        return this.factureses;
    }
    
    public void setFactureses(Set factureses) {
        this.factureses = factureses;
    }
    public Set getLignesCommandes() {
        return this.lignesCommandes;
    }
    
    public void setLignesCommandes(Set lignesCommandes) {
        this.lignesCommandes = lignesCommandes;
    }




}


