package Modele;
// Generated 2018-09-03 11:44:25 by Hibernate Tools 4.3.1



/**
 * IngredientsLangues generated by hbm2java
 */
public class IngredientsLangues  implements java.io.Serializable {


     private IngredientsLanguesId id;
     private Ingredients ingredients;
     private Langues langues;
     private String nomIngredients;

    public IngredientsLangues() {
    }

    public IngredientsLangues(IngredientsLanguesId id, Ingredients ingredients, Langues langues, String nomIngredients) {
       this.id = id;
       this.ingredients = ingredients;
       this.langues = langues;
       this.nomIngredients = nomIngredients;
    }
   
    public IngredientsLanguesId getId() {
        return this.id;
    }
    
    public void setId(IngredientsLanguesId id) {
        this.id = id;
    }
    public Ingredients getIngredients() {
        return this.ingredients;
    }
    
    public void setIngredients(Ingredients ingredients) {
        this.ingredients = ingredients;
    }
    public Langues getLangues() {
        return this.langues;
    }
    
    public void setLangues(Langues langues) {
        this.langues = langues;
    }
    public String getNomIngredients() {
        return this.nomIngredients;
    }
    
    public void setNomIngredients(String nomIngredients) {
        this.nomIngredients = nomIngredients;
    }




}


